// --- --- --- --- --- --- --- ---  APPS REDUCER ------------ ------------
export const appConstants = {
  GET_APPS_REQUEST: 'GET_APPS_REQUEST',
  GET_APPS_SUCCESS: 'GET_APPS_SUCCESS',
  GET_APPS_FAILURE: 'GET_APPS_FAILURE',

  ADD_APPS_REQUEST: 'ADD_APPS_REQUEST',
  ADD_APPS_SUCCESS: 'ADD_APPS_SUCCESS',
  ADD_APPS_FAILURE: 'ADD_APPS_FAILURE',
};

// --- --- --- --- --- --- --- ---  CAMPAIGNS REDUCER ------------ ------------
export const campaignsConstants = {
  GET_CAMPAIGNS_REQUEST: 'GET_CAMPAIGNS_REQUEST',
  GET_CAMPAIGNS_SUCCESS: 'GET_CAMPAIGNS_SUCCESS',
  GET_CAMPAIGNS_FAILURE: 'GET_CAMPAIGNS_FAILURE',

  SET_CAMPAIGN_DATA: 'SET_CAMPAIGN_DATA',

  ADD_CAMPAIGN_DATA: 'ADD_CAMPAIGN_DATA',
};
